version: "2"
services:
  redis:
    image: redis:3.0.7
    networks:
      - pds
    ports:
      - "6379:6379"
    volumes:
      - pds_redis:/var/lib/redis/data
  seaquill:
    image: quay.io/skuid/seaquill:master-1055
    networks:
      - pds
    ports:
      - "3113:3113"
    environment:
      - NODE_ENV=production
      - NEW_RELIC_ENABLED=false
      - SEAQUILL_PORT=3113
  clortho:
    image: quay.io/skuid/clortho:master-22
    ports:
      - "3009:3009"
    env_file:
      - ./env/clortho
    environment:
      - CLORTHO_PORT=3009
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - pds
  sluice:
    image: quay.io/skuid/sluice:master-58
    networks:
      - pds
    ports:
      - "3005:3005"
      - "80:80"
    environment:
      - WARDEN_HOST=http://warden:3004
  warden:
    image: "quay.io/skuid/warden:master-1642"
    networks:
      - pds
    ports:
      - "3004:3004"
    env_file:
      - ./env/warden
    environment:
      - WARDEN_PORT=3004
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WARDEN_QUILL_ADDRESS=http://seaquill:3113
      - WARDEN_CLORTHO_ADDRESS=http://clortho:3009
      - WARDEN_AUTHCACHE_TTL=5s
      - WARDEN_DATABASE_ON=true
      - WARDEN_GZIP_LOAD_PROXY=true
      - WARDEN_GZIP_LOAD_RESPONSE=true
      - WARDEN_STREAM=true
      - WARDEN_USE_KMS=false
      - WARDEN_DATADOG_ENABLED=false
    depends_on:
      - "redis"
      - "seaquill"

networks:
  pds:
    driver: bridge

volumes:
  pds_redis:
